import pandas as pd

df = pd.read_csv('test.csv')
df.head()

In [3]:
import torch
import torchmetrics

In [36]:
acc = torchmetrics.F1Score(num_classes=2, average='none')

ml_preds  = torch.tensor([[0.2, 0.7], [0.2, 0.6], [0.4, 0.9]])
ml_target = torch.tensor([[0, 0], [0, 0], [1, 1]])
#ml_preds  = torch.tensor([[0.2, 0.8, 0.9], [0.5, 0.6, 0.1], [0.3, 0.1, 0.1]])
#ml_target = torch.tensor([[0, 1, 1], [1, 0, 0], [0, 0, 0]])
acc(ml_preds, ml_target)

tensor([0.0000, 0.5000])

In [37]:
acc(1-ml_preds, 1-ml_target)

tensor([0.8000, 0.0000])

array([0.3, 0.1, 0.2], dtype=float32)

In [48]:
from sklearn.metrics import f1_score
ml_preds  = torch.tensor([1, 1, 1])
ml_target = torch.tensor([0, 0, 1])
f1_score(ml_preds.numpy(), ml_target.numpy(), pos_label=1)

0.5

In [49]:
f1_score(ml_preds.numpy(), ml_target.numpy(), pos_label=0)

0.0