In [1]:
import pandas as pd

df = pd.read_csv('test.csv')
df.head()

idtwitter  subj  opos  oneg  iro  lpos  lneg  top  \
0  507074506880712705     0     0     0    0     0     0    2   
1  507075789456961536     1     1     0    0     1     0    2   
2  507077511902425088     1     0     1    0     0     1    2   
3  507079183315787777     0     0     0    0     0     0    2   
4  507080190225563648     1     0     0    0     0     0    2   

                                                text  
0  Tra 5 minuti presentazione piano scuola del go...  
1  @matteorenzi: Alle 10 appuntamento su http://t...  
2  #labuonascuola gli #evangelisti #digitali non ...  
3  Riforma scuola Tutto il discorso di  Renzi su ...  
4  .@matteorenzi @MiurSocial #labuonascuola basta...

In [2]:
import torch
import torchmetrics

In [24]:
acc = torchmetrics.F1Score(num_classes=1, average='macro', multiclass=False)
pred = torch.tensor([[1], [0], [1], [0]])
targ = torch.tensor([[0], [0], [0], [0]])
acc(pred, targ)

tensor(0.)

In [25]:
acc(1-pred,1-targ)

tensor(0.6667)

In [9]:
from torch import tensor
n = [{'accuracy_macro': tensor(0.6583), 'accuracy_micro': tensor(0.6582), 'accuracy_none': tensor([0.7045, 0.7265, 0.6555, 0.5620, 0.6895, 0.6115]), 'accuracy_weighted': tensor(0.6497), 'f1_macro': tensor(0.6903), 'f1_micro': tensor(0.7132), 'f1_none': tensor([0.5386, 0.8244, 0.6692, 0.6784, 0.7871, 0.6437]), 'f1_weighted': tensor(0.7069), 'precision_macro': tensor(0.7542), 'precision_micro': tensor(0.7635), 'precision_none': tensor([0.5029, 0.7647, 0.7727, 0.9487, 0.7340, 0.8023]), 'precision_weighted': tensor(0.7888), 'recall_macro': tensor(0.6630), 'recall_micro': tensor(0.6692), 'recall_none': tensor([0.5798, 0.8942, 0.5902, 0.5280, 0.8485, 0.5375]), 'recall_weighted': tensor(0.6692)}, {'accuracy_macro': tensor(0.7076), 'accuracy_micro': tensor(0.7076), 'accuracy_none': tensor([0.7055, 0.6820, 0.7540, 0.6660, 0.6860, 0.7520]), 'accuracy_weighted': tensor(0.7040), 'f1_macro': tensor(0.7433), 'f1_micro': tensor(0.7566), 'f1_none': tensor([0.5826, 0.7531, 0.7977, 0.7773, 0.7437, 0.8052]), 'f1_weighted': tensor(0.7595), 'precision_macro': tensor(0.7866), 'precision_micro': tensor(0.8026), 'precision_none': tensor([0.5037, 0.8509, 0.7754, 0.9328, 0.8304, 0.8266]), 'precision_weighted': tensor(0.8231), 'recall_macro': tensor(0.7187), 'recall_micro': tensor(0.7155), 'recall_none': tensor([0.6908, 0.6755, 0.8213, 0.6663, 0.6733, 0.7848]), 'recall_weighted': tensor(0.7155)}, {'accuracy_macro': tensor(0.7517), 'accuracy_micro': tensor(0.7517), 'accuracy_none': tensor([0.7830, 0.7870, 0.7755, 0.6160, 0.7840, 0.7650]), 'accuracy_weighted': tensor(0.7413), 'f1_macro': tensor(0.7770), 'f1_micro': tensor(0.7870), 'f1_none': tensor([0.6583, 0.8426, 0.7975, 0.7279, 0.8318, 0.8042]), 'f1_weighted': tensor(0.7864), 'precision_macro': tensor(0.8482), 'precision_micro': tensor(0.8648), 'precision_none': tensor([0.6193, 0.8976, 0.8533, 0.9580, 0.8790, 0.8821]), 'precision_weighted': tensor(0.8769), 'recall_macro': tensor(0.7267), 'recall_micro': tensor(0.7220), 'recall_none': tensor([0.7025, 0.7939, 0.7485, 0.5869, 0.7894, 0.7389]), 'recall_weighted': tensor(0.7220)}, {'accuracy_macro': tensor(0.7728), 'accuracy_micro': tensor(0.7728), 'accuracy_none': tensor([0.7755, 0.8120, 0.7840, 0.6655, 0.8090, 0.7910]), 'accuracy_weighted': tensor(0.7670), 'f1_macro': tensor(0.8014), 'f1_micro': tensor(0.8118), 'f1_none': tensor([0.6753, 0.8650, 0.8107, 0.7713, 0.8552, 0.8309]), 'f1_weighted': tensor(0.8127), 'precision_macro': tensor(0.8407), 'precision_micro': tensor(0.8565), 'precision_none': tensor([0.5926, 0.8926, 0.8401, 0.9600, 0.8778, 0.8808]), 'precision_weighted': tensor(0.8719), 'recall_macro': tensor(0.7786), 'recall_micro': tensor(0.7716), 'recall_none': tensor([0.7849, 0.8391, 0.7832, 0.6446, 0.8337, 0.7864]), 'recall_weighted': tensor(0.7716)}, {'accuracy_macro': tensor(0.7981), 'accuracy_micro': tensor(0.7981), 'accuracy_none': tensor([0.7980, 0.8080, 0.7950, 0.7745, 0.8135, 0.7995]), 'accuracy_weighted': tensor(0.7970), 'f1_macro': tensor(0.8223), 'f1_micro': tensor(0.8347), 'f1_none': tensor([0.6985, 0.8589, 0.8228, 0.8599, 0.8563, 0.8373]), 'f1_weighted': tensor(0.8369), 'precision_macro': tensor(0.8508), 'precision_micro': tensor(0.8695), 'precision_none': tensor([0.6282, 0.9090, 0.8402, 0.9421, 0.8945, 0.8904]), 'precision_weighted': tensor(0.8783), 'recall_macro': tensor(0.8015), 'recall_micro': tensor(0.8025), 'recall_none': tensor([0.7866, 0.8141, 0.8061, 0.7909, 0.8211, 0.7902]), 'recall_weighted': tensor(0.8025)}, {'accuracy_macro': tensor(0.8018), 'accuracy_micro': tensor(0.8018), 'accuracy_none': tensor([0.8130, 0.7995, 0.7950, 0.7945, 0.8090, 0.7995]), 'accuracy_weighted': tensor(0.8004), 'f1_macro': tensor(0.8236), 'f1_micro': tensor(0.8366), 'f1_none': tensor([0.7069, 0.8513, 0.8205, 0.8738, 0.8523, 0.8368]), 'f1_weighted': tensor(0.8381), 'precision_macro': tensor(0.8589), 'precision_micro': tensor(0.8779), 'precision_none': tensor([0.6623, 0.9104, 0.8495, 0.9443, 0.8938, 0.8931]), 'precision_weighted': tensor(0.8834), 'recall_macro': tensor(0.7943), 'recall_micro': tensor(0.7990), 'recall_none': tensor([0.7580, 0.7994, 0.7934, 0.8131, 0.8145, 0.7871]), 'recall_weighted': tensor(0.7990)}]
p = [{'accuracy_macro': tensor(0.6583), 'accuracy_micro': tensor(0.6582), 'accuracy_none': tensor([0.7045, 0.7265, 0.6555, 0.5620, 0.6895, 0.6115]), 'accuracy_weighted': tensor(0.6731), 'f1_macro': tensor(0.5197), 'f1_micro': tensor(0.5772), 'f1_none': tensor([0.7826, 0.3819, 0.6406, 0.3135, 0.4266, 0.5728]), 'f1_weighted': tensor(0.5918), 'precision_macro': tensor(0.5139), 'precision_micro': tensor(0.5261), 'precision_none': tensor([0.8097, 0.5265, 0.5592, 0.1949, 0.5298, 0.4631]), 'precision_weighted': tensor(0.5950), 'recall_macro': tensor(0.6191), 'recall_micro': tensor(0.6392), 'recall_none': tensor([0.7573, 0.2996, 0.7497, 0.8000, 0.3570, 0.7507]), 'recall_weighted': tensor(0.6392)}, {'accuracy_macro': tensor(0.7076), 'accuracy_micro': tensor(0.7076), 'accuracy_none': tensor([0.7055, 0.6820, 0.7540, 0.6660, 0.6860, 0.7520]), 'accuracy_weighted': tensor(0.7138), 'f1_macro': tensor(0.5996), 'f1_micro': tensor(0.6339), 'f1_none': tensor([0.7725, 0.5534, 0.6862, 0.3320, 0.5948, 0.6589]), 'f1_weighted': tensor(0.6587), 'precision_macro': tensor(0.5639), 'precision_micro': tensor(0.5836), 'precision_none': tensor([0.8446, 0.4581, 0.7183, 0.2213, 0.5105, 0.6303]), 'precision_weighted': tensor(0.6523), 'recall_macro': tensor(0.6890), 'recall_micro': tensor(0.6938), 'recall_none': tensor([0.7117, 0.6986, 0.6569, 0.6640, 0.7125, 0.6902]), 'recall_weighted': tensor(0.6938)}, {'accuracy_macro': tensor(0.7517), 'accuracy_micro': tensor(0.7517), 'accuracy_none': tensor([0.7830, 0.7870, 0.7755, 0.6160, 0.7840, 0.7650]), 'accuracy_weighted': tensor(0.7699), 'f1_macro': tensor(0.6688), 'f1_micro': tensor(0.7026), 'f1_none': tensor([0.8410, 0.6708, 0.7482, 0.3480, 0.6983, 0.7063]), 'f1_weighted': tensor(0.7311), 'precision_macro': tensor(0.6057), 'precision_micro': tensor(0.6242), 'precision_none': tensor([0.8664, 0.5945, 0.6919, 0.2209, 0.6369, 0.6236]), 'precision_weighted': tensor(0.6895), 'recall_macro': tensor(0.8013), 'recall_micro': tensor(0.8036), 'recall_none': tensor([0.8171, 0.7695, 0.8144, 0.8200, 0.7728, 0.8141]), 'recall_weighted': tensor(0.8036)}, {'accuracy_macro': tensor(0.7728), 'accuracy_micro': tensor(0.7728), 'accuracy_none': tensor([0.7755, 0.8120, 0.7840, 0.6655, 0.8090, 0.7910]), 'accuracy_weighted': tensor(0.7829), 'f1_macro': tensor(0.6818), 'f1_micro': tensor(0.7135), 'f1_none': tensor([0.8284, 0.6903, 0.7485, 0.3777, 0.7195, 0.7264]), 'f1_weighted': tensor(0.7377), 'precision_macro': tensor(0.6418), 'precision_micro': tensor(0.6610), 'precision_none': tensor([0.8944, 0.6446, 0.7152, 0.2461, 0.6853, 0.6655]), 'precision_weighted': tensor(0.7245), 'recall_macro': tensor(0.7781), 'recall_micro': tensor(0.7751), 'recall_none': tensor([0.7715, 0.7429, 0.7851, 0.8120, 0.7573, 0.7997]), 'recall_weighted': tensor(0.7751)}, {'accuracy_macro': tensor(0.7981), 'accuracy_micro': tensor(0.7981), 'accuracy_none': tensor([0.7980, 0.8080, 0.7950, 0.7745, 0.8135, 0.7995]), 'accuracy_weighted': tensor(0.7999), 'f1_macro': tensor(0.7000), 'f1_micro': tensor(0.7407), 'f1_none': tensor([0.8481, 0.6995, 0.7568, 0.4225, 0.7345, 0.7388]), 'f1_weighted': tensor(0.7535), 'precision_macro': tensor(0.6544), 'precision_micro': tensor(0.6969), 'precision_none': tensor([0.8988, 0.6261, 0.7359, 0.3107, 0.6807, 0.6742]), 'precision_weighted': tensor(0.7318), 'recall_macro': tensor(0.7748), 'recall_micro': tensor(0.7904), 'recall_none': tensor([0.8028, 0.7926, 0.7790, 0.6600, 0.7975, 0.8170]), 'recall_weighted': tensor(0.7904)}, {'accuracy_macro': tensor(0.8018), 'accuracy_micro': tensor(0.8018), 'accuracy_none': tensor([0.8130, 0.7995, 0.7950, 0.7945, 0.8090, 0.7995]), 'accuracy_weighted': tensor(0.8041), 'f1_macro': tensor(0.7055), 'f1_micro': tensor(0.7481), 'f1_none': tensor([0.8627, 0.6922, 0.7611, 0.4468, 0.7298, 0.7401]), 'f1_weighted': tensor(0.7589), 'precision_macro': tensor(0.6519), 'precision_micro': tensor(0.6975), 'precision_none': tensor([0.8908, 0.6103, 0.7280, 0.3367, 0.6728, 0.6726]), 'precision_weighted': tensor(0.7258), 'recall_macro': tensor(0.7863), 'recall_micro': tensor(0.8066), 'recall_none': tensor([0.8363, 0.7996, 0.7973, 0.6640, 0.7975, 0.8228]), 'recall_weighted': tensor(0.8066)}]

n[5], p[5]

({'accuracy_macro': tensor(0.8018),
  'accuracy_micro': tensor(0.8018),
  'accuracy_none': tensor([0.8130, 0.7995, 0.7950, 0.7945, 0.8090, 0.7995]),
  'accuracy_weighted': tensor(0.8004),
  'f1_macro': tensor(0.8236),
  'f1_micro': tensor(0.8366),
  'f1_none': tensor([0.7069, 0.8513, 0.8205, 0.8738, 0.8523, 0.8368]),
  'f1_weighted': tensor(0.8381),
  'precision_macro': tensor(0.8589),
  'precision_micro': tensor(0.8779),
  'precision_none': tensor([0.6623, 0.9104, 0.8495, 0.9443, 0.8938, 0.8931]),
  'precision_weighted': tensor(0.8834),
  'recall_macro': tensor(0.7943),
  'recall_micro': tensor(0.7990),
  'recall_none': tensor([0.7580, 0.7994, 0.7934, 0.8131, 0.8145, 0.7871]),
  'recall_weighted': tensor(0.7990)},
 {'accuracy_macro': tensor(0.8018),
  'accuracy_micro': tensor(0.8018),
  'accuracy_none': tensor([0.8130, 0.7995, 0.7950, 0.7945, 0.8090, 0.7995]),
  'accuracy_weighted': tensor(0.8041),
  'f1_macro': tensor(0.7055),
  'f1_micro': tensor(0.7481),
  'f1_none': tensor([0.8627

In [35]:
(42+93)/2

67.5

In [36]:
acc = torchmetrics.F1Score(num_classes=2, average='none')

ml_preds  = torch.tensor([[0.2, 0.7], [0.2, 0.6], [0.4, 0.9]])
ml_target = torch.tensor([[0, 0], [0, 0], [1, 1]])
#ml_preds  = torch.tensor([[0.2, 0.8, 0.9], [0.5, 0.6, 0.1], [0.3, 0.1, 0.1]])
#ml_target = torch.tensor([[0, 1, 1], [1, 0, 0], [0, 0, 0]])
acc(ml_preds, ml_target)

tensor([0.0000, 0.5000])

In [37]:
acc(1-ml_preds, 1-ml_target)

tensor([0.8000, 0.0000])

array([0.3, 0.1, 0.2], dtype=float32)

In [48]:
from sklearn.metrics import f1_score
ml_preds  = torch.tensor([1, 1, 1])
ml_target = torch.tensor([0, 0, 1])
f1_score(ml_preds.numpy(), ml_target.numpy(), pos_label=1)

0.5

In [49]:
f1_score(ml_preds.numpy(), ml_target.numpy(), pos_label=0)

0.0

In [3]:
a = torch.tensor([0.6958, 0.5843, 0.6672, 0.3805, 0.6305, 0.6678])
b = torch.tensor([0.6840, 0.8810, 0.8428, 0.9292, 0.8836, 0.8684])
(a + b) / 2

tensor([0.6899, 0.7326, 0.7550, 0.6549, 0.7571, 0.7681])